# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from config import *
from sys import argv
from webbrowser import open
from soup import connector
import pyautogui

frameless = None
x,y = pyautogui.position()[0], pyautogui.position()[1]

try:
    data = connector()
except:
    data = {
        "today" : {
            "temp" : "Undefined",
            "status" : "Undefined",
        },
        "tomorrow" : {
            "status" : "Undefined"
        }
    }


data["today"]["status"] = data["today"]["status"].replace("\n", "<br>Status: ")

try:
    arg = argv[1]
    if arg == "frameless":
        frameless = True
    else:
        frameless = False
except:
    frameless = False

def github_link():
    open('https://github.com/kinite-gp/weather_widget')


class Ui_Form(object):
    def setupUi(self, Form):
        if not frameless:
            Form.setWindowFlag(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setObjectName("Form")
        Form.resize(320, 240)
        Form.setStyleSheet("background-color: rgb(35, 37, 46);")
        self.title = QtWidgets.QLabel(parent=Form)
        self.title.setGeometry(QtCore.QRect(10, 10, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        self.title.setFont(font)
        self.title.setStyleSheet("color: rgb(255, 193, 7);")
        self.title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.title.setObjectName("title")
        self.area_value = QtWidgets.QLabel(parent=Form)
        self.area_value.setGeometry(QtCore.QRect(10, 40, 301, 30))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.area_value.setFont(font)
        self.area_value.setStyleSheet("color: rgb(255, 255, 255);")
        self.area_value.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.area_value.setObjectName("area_value")
        self.Today = QtWidgets.QTextBrowser(parent=Form)
        self.Today.setGeometry(QtCore.QRect(10, 80, 301, 121))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setKerning(True)
        self.Today.setFont(font)
        self.Today.setStyleSheet("color: rgb(255, 255, 255);")
        self.Today.setObjectName("Today")
        self.github = QtWidgets.QToolButton(parent=Form)
        self.github.setGeometry(QtCore.QRect(290, 210, 23, 21))
        self.github.setStyleSheet("color: rgb(255, 255, 255);")
        self.github.setObjectName("github")
        self.tomorrow = QtWidgets.QLabel(parent=Form)
        self.tomorrow.setGeometry(QtCore.QRect(10, 210, 271, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tomorrow.setFont(font)
        self.tomorrow.setStyleSheet("color: rgb(255, 255, 255);")
        self.tomorrow.setObjectName("tomorrow")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.title.setText(_translate("Form", "** Weather **"))
        self.area_value.setText(_translate("Form", "gorgan golestan"))
        self.Today.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Today</span></p>\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">{data['today']['status']}</span></p>\n"
f"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Temperature: {data['today']['temp']}</span></p></body></html>"))
        self.github.setText(_translate("Form", "GIT"))
        self.tomorrow.setText(_translate("Form", f"Tomorrow: {data['tomorrow']['status']}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.move(x,y)
    Form.show()
    if not frameless:
        QtCore.QTimer.singleShot(CLOSE_AFTER, Form.close)
    sys.exit(app.exec())
